services:

  node1:
    build: .
    container_name: node1
    command: python src/node.py 1
    volumes:
      - ./keys:/app/keys
      - ./ledgers:/app/ledgers

  node2:
    build: .
    container_name: node2
    command: python src/node.py 2
    volumes:
      - ./keys:/app/keys
      - ./ledgers:/app/ledgers

  node3:
    build: .
    container_name: node3
    command: python src/node.py 3
    volumes:
      - ./keys:/app/keys
      - ./ledgers:/app/ledgers

  node4:
    build: .
    container_name: node4
    command: python src/node.py 4
    volumes:
      - ./keys:/app/keys
      - ./ledgers:/app/ledgers

  node5:
    build: .
    container_name: node5
    command: python src/node.py 5
    volumes:
      - ./keys:/app/keys
      - ./ledgers:/app/ledgers

  # node5:
  #   build: .
  #   container_name: node5
  #   command: python src/adversary.py 5

  toxiproxy:
    image: shopify/toxiproxy
    container_name: toxiproxy
    ports:
      - "8474:8474"
      - "7001:7001"
      - "7002:7002"
      - "7003:7003"
      - "7004:7004"
      - "7005:7005"